resources:
  - bucket_prefix: test
    force_destroy: false
    acl: private
    expiration: 0
    expiration_test: 7
    object_ownership: BucketOwnerEnforced
    versioning_configuration_status: Disabled
    disable_ss3_s3: false
